export const SWITCH_LIGHT = "SWITCH_LIGHT";
export const GET_KITCHEN_LAMP_STATE = "GET_KITCHEN_LAMP_STATE ";
export const GET_LIVINGROOM_LAMP_STATE = "GET_LIVINGROOM_LAMP_STATE ";
export const GET_KITCHEN_WINDOW_STATE = "GET_KITCHEN_WINDOW_STATE ";
export const GET_LIVINGROOM_WINDOW_STATE = "GET_LIVINGROOM_WINDOW_STATE ";
export const SWITCH_WINDOW= "SWITCH_WINDOW";
export const GET_TEMPERATURE= "GET_TEMPERATURE";